title: Forgenst
email: ed@forgenst.com
description: >- # this means to ignore newlines until "baseurl:"
  Forgenst Homepage
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://forgenst.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/images/forgenst.png"
forum: "https://forum.forgenst.com"

collections:
  projects:
    output: True

collections:
  - apps